[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
  -DLOG_LOCAL_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DCORE_DEBUG_LEVEL=3
  -DHIGHER_CHARGE_CURRENT=1

[env:waveshare-esp32-s3-touch-amoled-18]
board = waveshare-esp32-s3-touch-amoled-18
board_build.embed_files = 
  assets/icons/battery_white.png
  assets/icons/charging_icon.bmp
  assets/icons/manual.bmp
  assets/icons/auto.bmp
  assets/icons/playlist.bmp

board_build.partitions = partitions.csv
lib_deps =
  https://github.com/bitbank2/bb_spi_lcd
  https://github.com/bitbank2/AnimatedGIF
  https://github.com/bitbank2/JPEGDEC
  https://github.com/bitbank2/PNGdec
  libs/Adafruit_XCA9554
  libs/XPowersLib
  https://github.com/adafruit/Adafruit-GFX-Library
